// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjUyuDAPXu8bFoWcBSZCLgfTX1Y-VoHx0',
    appId: '1:745804421317:web:e51a3b05cfbef0c95938ac',
    messagingSenderId: '745804421317',
    projectId: 'resport-app-db',
    authDomain: 'resport-app-db.firebaseapp.com',
    databaseURL: 'https://resport-app-db-default-rtdb.firebaseio.com',
    storageBucket: 'resport-app-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClTeuFByLRrhE9nfG6J_RPobypyv90a9Q',
    appId: '1:745804421317:ios:5c6106859bf4805e5938ac',
    messagingSenderId: '745804421317',
    projectId: 'resport-app-db',
    databaseURL: 'https://resport-app-db-default-rtdb.firebaseio.com',
    storageBucket: 'resport-app-db.firebasestorage.app',
    iosClientId: '745804421317-5a2sr1nvou6gd1kpf9kf3uka90p6n4is.apps.googleusercontent.com',
    iosBundleId: 'com.RESP0RT.Resport',
  );
}
