// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjUyuDAPXu8bFoWcBSZCLgfTX1Y-VoHx0',
    appId: '1:745804421317:web:3cdac06babdfd4815938ac',
    messagingSenderId: '745804421317',
    projectId: 'resport-app-db',
    authDomain: 'resport-app-db.firebaseapp.com',
    storageBucket: 'resport-app-db.firebasestorage.app',
    databaseURL: 'https://resport-app-db-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAwqi2HdmzPWqjQrGNq4tCXAZwjzLX71s',
    appId: '1:745804421317:android:181c7a71200a14d45938ac',
    messagingSenderId: '745804421317',
    projectId: 'resport-app-db',
    storageBucket: 'resport-app-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClTeuFByLRrhE9nfG6J_RPobypyv90a9Q',
    appId: '1:745804421317:ios:7a255edc112d527d5938ac',
    messagingSenderId: '745804421317',
    projectId: 'resport-app-db',
    storageBucket: 'resport-app-db.firebasestorage.app',
    iosBundleId: 'com.nikhilsinha.resportcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClTeuFByLRrhE9nfG6J_RPobypyv90a9Q',
    appId: '1:745804421317:ios:f89c99e730355ed75938ac',
    messagingSenderId: '745804421317',
    projectId: 'resport-app-db',
    storageBucket: 'resport-app-db.firebasestorage.app',
    iosBundleId: 'com.example.resportcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjUyuDAPXu8bFoWcBSZCLgfTX1Y-VoHx0',
    appId: '1:745804421317:web:af0f8cf61399cf095938ac',
    messagingSenderId: '745804421317',
    projectId: 'resport-app-db',
    authDomain: 'resport-app-db.firebaseapp.com',
    storageBucket: 'resport-app-db.firebasestorage.app',
  );

}